
import { Book } from './types';

export const BOOKS_LIST: Book[] = [
  { id: 1, year: 1776, titleEn: "The Wealth of Nations", titleVi: "Sự Giàu Có Của Các Quốc Gia", author: "Adam Smith", category: "Kinh tế" },
  { id: 2, year: 1835, titleEn: "Democracy in America", titleVi: "Nền Dân Trị Mỹ", author: "Alexis de Tocqueville", category: "Chính trị" },
  { id: 3, year: 1905, titleEn: "The Protestant Ethic and the Spirit of Capitalism", titleVi: "Đạo Đức Tin Lành Và Tinh Thần Chủ Nghĩa Tư Bản", author: "Max Weber", category: "Xã hội" },
  { id: 4, year: 1911, titleEn: "The Theory of Economic Development", titleVi: "Lý Thuyết Phát Triển Kinh Tế", author: "Joseph A. Schumpeter", category: "Kinh tế" },
  { id: 5, year: 1942, titleEn: "Capitalism, Socialism and Democracy", titleVi: "Chủ Nghĩa Tư Bản, Chủ Nghĩa Xã Hội Và Dân Chủ", author: "Joseph A. Schumpeter", category: "Chính trị" },
  { id: 6, year: 1944, titleEn: "The Road to Serfdom", titleVi: "Đường Về Nô Lệ", author: "Friedrich Hayek", category: "Kinh tế" },
  { id: 7, year: 1944, titleEn: "The Great Transformation", titleVi: "Sự Biến Đổi Lớn", author: "Karl Polanyi", category: "Lịch sử" },
  { id: 8, year: 1960, titleEn: "The Stages of Economic Growth", titleVi: "Các Giai Đoạn Tăng Trưởng Kinh Tế", author: "W.W. Rostow", category: "Kinh tế" },
  { id: 9, year: 1962, titleEn: "The Structure of Scientific Revolutions", titleVi: "Cấu Trúc Các Cuộc Cách Mạng Khoa Học", author: "Thomas S. Kuhn", category: "Khoa học" },
  { id: 10, year: 1963, titleEn: "The Rise of the West", titleVi: "Sự Trỗi Dậy Của Phương Tây", author: "William H. McNeill", category: "Lịch sử" },
  { id: 11, year: 1965, titleEn: "The Logic of Collective Action", titleVi: "Logic Của Hành Động Tập Thể", author: "Mancur Olson", category: "Xã hội" },
  { id: 12, year: 1968, titleEn: "The Economy of Cities", titleVi: "Nền Kinh Tế Của Các Thành Phố", author: "Jane Jacobs", category: "Kinh tế" },
  { id: 13, year: 1974, titleEn: "The Modern World-System", titleVi: "Hệ Thống Thế Giới Hiện Đại", author: "Immanuel Wallerstein", category: "Lịch sử" },
  { id: 14, year: 1976, titleEn: "Plagues and Peoples", titleVi: "Dịch Bệnh Và Các Dân Tộc", author: "William H. McNeill", category: "Lịch sử" },
  { id: 15, year: 1982, titleEn: "The Rise and Decline of Nations", titleVi: "Sự Trỗi Dậy Và Suy Tàn Của Các Quốc Gia", author: "Mancur Olson", category: "Kinh tế" },
  { id: 16, year: 1988, titleEn: "The Passion of the Western Mind", titleVi: "Đam Mê Của Trí Tuệ Phương Tây", author: "Richard Tarnas", category: "Xã hội" },
  { id: 17, year: 1990, titleEn: "Institutions, Institutional Change and Economic Performance", titleVi: "Thể Chế, Thay Đổi Thể Chế Và Kết Quả Kinh Tế", author: "Douglass North", category: "Kinh tế" },
  { id: 18, year: 1991, titleEn: "The Third Wave: Democratization in the Late Twentieth Century", titleVi: "Làn Sóng Thứ Ba: Dân Chủ Hóa Cuối Thế Kỷ 20", author: "Samuel P. Huntington", category: "Chính trị" },
  { id: 19, year: 1992, titleEn: "The End of History and the Last Man", titleVi: "Sự Kết Thúc Của Lịch Sử Và Con Người Cuối Cùng", author: "Francis Fukuyama", category: "Chính trị" },
  { id: 20, year: 1993, titleEn: "Making Democracy Work", titleVi: "Làm Cho Dân Chủ Vận Hành", author: "Robert Putnam", category: "Chính trị" },
  { id: 21, year: 1994, titleEn: "The Long Twentieth Century", titleVi: "Thế Kỷ 20 Dài", author: "Giovanni Arrighi", category: "Lịch sử" },
  { id: 22, year: 1995, titleEn: "Trust: The Social Virtues and the Creation of Prosperity", titleVi: "Niềm Tin: Các Đức Hạnh Xã Hội Và Sự Tạo Ra Thịnh Vượng", author: "Francis Fukuyama", category: "Xã hội" },
  { id: 23, year: 1996, titleEn: "The Clash of Civilizations", titleVi: "Sự Va Chạm Của Các Nền Văn Minh", author: "Samuel P. Huntington", category: "Chính trị" },
  { id: 24, year: 1997, titleEn: "Guns, Germs, and Steel", titleVi: "Súng, Vi Trùng Và Thép", author: "Jared Diamond", category: "Lịch sử" },
  { id: 25, year: 1998, titleEn: "The Wealth and Poverty of Nations", titleVi: "Sự Giàu Có Và Nghèo Khổ Của Các Dân Tộc", author: "David S. Landes", category: "Lịch sử" },
  { id: 26, year: 1998, titleEn: "Seeing Like a State", titleVi: "Cái Nhìn Của Nhà Nước", author: "James C. Scott", category: "Chính trị" },
  { id: 27, year: 1999, titleEn: "Development as Freedom", titleVi: "Phát Triển Là Tự Do", author: "Amartya Sen", category: "Kinh tế" },
  { id: 28, year: 2000, titleEn: "States and Power in Africa", titleVi: "Nhà Nước Và Quyền Lực Ở Châu Phi", author: "Jeffrey Herbst", category: "Chính trị" },
  { id: 29, year: 2000, titleEn: "The Mystery of Capital", titleVi: "Bí Ẩn Của Vốn", author: "Hernando de Soto", category: "Kinh tế" },
  { id: 30, year: 2000, titleEn: "Culture Matters", titleVi: "Văn Hóa Quan Trọng", author: "Lawrence E. Harrison", category: "Xã hội" },
  { id: 31, year: 2000, titleEn: "Bowling Alone", titleVi: "Đi Chơi Bowling Một Mình", author: "Robert Putnam", category: "Xã hội" },
  { id: 32, year: 2001, titleEn: "The Elusive Quest for Growth", titleVi: "Cuộc Tìm Kiếm Sự Tăng Trưởng Khó Khăn", author: "William Easterly", category: "Kinh tế" },
  { id: 33, year: 2002, titleEn: "The Shield of Achilles", titleVi: "Khiên Của Achilles", author: "Philip Bobbitt", category: "Chính trị" },
  { id: 34, year: 2002, titleEn: "Technological Revolutions and Financial Capital", titleVi: "Cách Mạng Công Nghệ Và Vốn Tài Chính", author: "Carlota Perez", category: "Kinh tế" },
  { id: 35, year: 2002, titleEn: "Globalization and Its Discontents", titleVi: "Toàn Cầu Hóa Và Những Mặt Trái Của Nó", author: "Joseph Stiglitz", category: "Kinh tế" },
  { id: 36, year: 2003, titleEn: "The Geography of Thought", titleVi: "Địa Lý Của Tư Duy", author: "Richard Nisbett", category: "Xã hội" },
  { id: 37, year: 2005, titleEn: "Collapse", titleVi: "Sụp Đổ", author: "Jared Diamond", category: "Lịch sử" },
  { id: 38, year: 2005, titleEn: "The World Is Flat", titleVi: "Thế Giới Phẳng", author: "Thomas L. Friedman", category: "Xã hội" },
  { id: 39, year: 2006, titleEn: "The White Man's Burden", titleVi: "Gánh Nặng Của Người Da Trắng", author: "William Easterly", category: "Kinh tế" },
  { id: 40, year: 2007, titleEn: "Bad Samaritans", titleVi: "Những Người Samari Tốt Bụng (Không Phải Thế)", author: "Ha-Joon Chang", category: "Kinh tế" },
  { id: 41, year: 2007, titleEn: "The Bottom Billion", titleVi: "Một Tỷ Người Nghèo Nhất", author: "Paul Collier", category: "Kinh tế" },
  { id: 42, year: 2009, titleEn: "The Spirit Level", titleVi: "Mức Độ Tinh Thần", author: "Richard Wilkinson", category: "Xã hội" },
  { id: 43, year: 2010, titleEn: "How Asia Works", titleVi: "Châu Á Vận Hành Như Thế Nào", author: "Joe Studwell", category: "Kinh tế" },
  { id: 44, year: 2010, titleEn: "Why the West Rules—for Now", titleVi: "Tại Sao Phương Tây Thống Trị", author: "Ian Morris", category: "Lịch sử" },
  { id: 45, year: 2011, titleEn: "The Origins of Political Order", titleVi: "Nguồn Gốc Của Trật Tự Chính Trị", author: "Francis Fukuyama", category: "Chính trị" },
  { id: 46, year: 2011, titleEn: "The Globalization Paradox", titleVi: "Nghịch Lý Toàn Cầu Hóa", author: "Dani Rodrik", category: "Kinh tế" },
  { id: 47, year: 2011, titleEn: "Sapiens: A Brief History of Humankind", titleVi: "Sapiens: Lược Sử Loài Người", author: "Yuval Noah Harari", category: "Lịch sử" },
  { id: 48, year: 2011, titleEn: "The Dictator's Handbook", titleVi: "Cẩm Nang Của Kẻ Độc Tài", author: "Bruce Bueno de Mesquita", category: "Chính trị" },
  { id: 49, year: 2011, titleEn: "Poor Economics", titleVi: "Kinh Tế Học Nghèo Khổ", author: "Abhijit Banerjee", category: "Kinh tế" },
  { id: 50, year: 2011, titleEn: "The Better Angels of Our Nature", titleVi: "Những Thiên Thần Tốt Trong Bản Tính Chúng Ta", author: "Steven Pinker", category: "Xã hội" },
  { id: 51, year: 2011, titleEn: "Civilization: The West and the Rest", titleVi: "Văn Minh: Phương Tây Và Phần Còn Lại", author: "Niall Ferguson", category: "Lịch sử" },
  { id: 52, year: 2011, titleEn: "The Strategy of Economic Development", titleVi: "Chiến Lược Phát Triển Kinh Tế", author: "Albert O. Hirschman", category: "Kinh tế" },
  { id: 53, year: 2012, titleEn: "Why Nations Fail", titleVi: "Tại Sao Các Quốc Gia Thất Bại", author: "Daron Acemoglu", category: "Chính trị" },
  { id: 54, year: 2012, titleEn: "Antifragile", titleVi: "Khả Năng Chống Chọi Với Nghịch Cảnh", author: "Nassim Nicholas Taleb", category: "Khoa học" },
  { id: 55, year: 2013, titleEn: "The Great Escape", titleVi: "Cuộc Thoát Hiểm Lớn", author: "Angus Deaton", category: "Kinh tế" },
  { id: 56, year: 2013, titleEn: "Capital in the Twenty-First Century", titleVi: "Tư Bản Thế Kỷ 21", author: "Thomas Piketty", category: "Kinh tế" },
  { id: 57, year: 2013, titleEn: "The New Digital Age", titleVi: "Kỷ Nguyên Số Mới", author: "Eric Schmidt", category: "Công nghệ" },
  { id: 58, year: 2014, titleEn: "The Second Machine Age", titleVi: "Kỷ Nguyên Máy Móc Thứ Hai", author: "Erik Brynjolfsson", category: "Công nghệ" },
  { id: 59, year: 2014, titleEn: "The Tyranny of Experts", titleVi: "Sự Chuyên Quyền Của Chuyên Gia", author: "William Easterly", category: "Kinh tế" },
  { id: 60, year: 2014, titleEn: "The Culture Map", titleVi: "Bản Đồ Văn Hóa", author: "Erin Meyer", category: "Xã hội" },
  { id: 61, year: 2014, titleEn: "Superintelligence", titleVi: "Siêu Trí Tuệ", author: "Nick Bostrom", category: "Công nghệ" },
  { id: 62, year: 2015, titleEn: "Prisoners of Geography", titleVi: "Những Tù Nhân Của Địa Lý", author: "Tim Marshall", category: "Chính trị" },
  { id: 63, year: 2015, titleEn: "The Rise and Fall of American Growth", titleVi: "Sự Trỗi Dậy Và Suy Tàn Của Tăng Trưởng Mỹ", author: "Robert J. Gordon", category: "Kinh tế" },
  { id: 64, year: 2016, titleEn: "Global Inequality", titleVi: "Bất Bình Đẳng Toàn Cầu", author: "Branko Milanovic", category: "Kinh tế" },
  { id: 65, year: 2017, titleEn: "The Great Leveler", titleVi: "Sự Cân Bằng Lớn", author: "Walter Scheidel", category: "Lịch sử" },
  { id: 66, year: 2018, titleEn: "AI Superpowers", titleVi: "Các Siêu Cường AI", author: "Kai-Fu Lee", category: "Công nghệ" },
  { id: 67, year: 2018, titleEn: "Globalists", titleVi: "Những Người Toầu Cầu Hóa", author: "Quinn Slobodian", category: "Chính trị" },
  { id: 68, year: 2018, titleEn: "The Future of Capitalism", titleVi: "Tương Lai Của Chủ Nghĩa Tư Bản", author: "Paul Collier", category: "Kinh tế" },
  { id: 69, year: 2018, titleEn: "The People vs. Democracy", titleVi: "Nhân Dân Chống Lại Dân Chủ", author: "Yascha Mounk", category: "Chính trị" },
  { id: 70, year: 2018, titleEn: "The Square and the Tower", titleVi: "Quảng Trường Và Tòa Tháp", author: "Niall Ferguson", category: "Lịch sử" },
  { id: 71, year: 2018, titleEn: "How Democracies Die", titleVi: "Dân Chủ Chết Như Thế Nào", author: "Steven Levitsky", category: "Chính trị" },
  { id: 72, year: 2019, titleEn: "The Narrow Corridor", titleVi: "Hành Lang Hẹp", author: "Daron Acemoglu", category: "Chính trị" },
  { id: 73, year: 2019, titleEn: "The Third Pillar", titleVi: "Cột Trụ Thứ Ba", author: "Raghuram Rajan", category: "Xã hội" },
  { id: 74, year: 2019, titleEn: "The Meritocracy Trap", titleVi: "Bẫy Chế Độ Tài Năng", author: "Daniel Markovits", category: "Xã hội" },
  { id: 75, year: 2019, titleEn: "The Age of Surveillance Capitalism", titleVi: "Kỷ Nguyên Chủ Nghĩa Tư Bản Giám Sát", author: "Shoshana Zuboff", category: "Xã hội" },
  { id: 76, year: 2019, titleEn: "The Age of Unpeace", titleVi: "Kỷ Nguyên Bất Hòa", author: "Mark Leonard", category: "Chính trị" },
  { id: 77, year: 2020, titleEn: "The Ministry for the Future", titleVi: "Bộ Tương Lai", author: "Kim Stanley Robinson", category: "Công nghệ" },
  { id: 78, year: 2020, titleEn: "China's Gilded Age", titleVi: "Thời Đại Vàng Của Trung Quốc", author: "Yuen Yuen Ang", category: "Chính trị" },
  { id: 79, year: 2020, titleEn: "The Gilded Cage", titleVi: "Chiếc Lồng Vàng", author: "Techno-Capitalism Study", category: "Xã hội" },
  { id: 80, year: 2020, titleEn: "Connectography", titleVi: "Kết Nối Học", author: "Parag Khanna", category: "Lịch sử" },
  { id: 81, year: 2021, titleEn: "Data and Goliath", titleVi: "Dữ Liệu Và Goliath", author: "Bruce Schneier", category: "Công nghệ" },
  { id: 82, year: 2021, titleEn: "Underwater", titleVi: "Dưới Nước", author: "Rebecca Elliott", category: "Khoa học" },
  { id: 83, year: 2022, titleEn: "The Power Law", titleVi: "Luật Lực", author: "Sebastian Mallaby", category: "Kinh tế" },
  { id: 84, year: 2022, titleEn: "The Wizard and the Prophet", titleVi: "Phù Thủy Và Nhà Tiên Tri", author: "Charles C. Mann", category: "Khoa học" },
  { id: 85, year: 2022, titleEn: "The Next Great Migration", titleVi: "Cuộc Đại Di Cư Tiếp Theo", author: "Sonia Shah", category: "Xã hội" },
  { id: 86, year: 2023, titleEn: "Escape from Rome", titleVi: "Thoát Khỏi Rome", author: "Walter Scheidel", category: "Lịch sử" },
  { id: 87, year: 2023, titleEn: "Chip War", titleVi: "Cuộc Chiến Chip", author: "Chris Miller", category: "Công nghệ" },
  { id: 88, year: 2024, titleEn: "The Vision of Finance", titleVi: "Tầm Nhìn Tài Chính", author: "Kim Perell", category: "Kinh tế" },
  { id: 89, year: 2024, titleEn: "Chip War (Latest Ed)", titleVi: "Cuộc Chiến Chip (Tái Bản)", author: "Chris Miller", category: "Công nghệ" },
  { id: 90, year: 2024, titleEn: "The Loop", titleVi: "Vòng Lặp", author: "Jacob Ward", category: "Công nghệ" },
  { id: 91, year: 2025, titleEn: "The Coming Wave", titleVi: "Làn Sóng Sắp Đến", author: "Mustafa Suleyman", category: "Công nghệ" },
  { id: 92, year: 2025, titleEn: "Power and Progress", titleVi: "Quyền Lực Và Tiến Bộ", author: "Daron Acemoglu", category: "Kinh tế" },
  { id: 93, year: 2025, titleEn: "A Question of Power", titleVi: "Vấn Đề Quyền Lực", author: "Robert Bryce", category: "Chính trị" },
  { id: 94, year: 2025, titleEn: "The Resilience Dividend", titleVi: "Cổ Tức Khả Năng Chống Chịu", author: "Judith Rodin", category: "Kinh tế" },
  { id: 95, year: 2026, titleEn: "The Climate Change Economy", titleVi: "Kinh Tế Biến Đổi Khí Hậu", author: "William Nordhaus", category: "Kinh tế" }
];
